from django import forms
from django.conf import settings

class TTAdminDateWidget(forms.DateInput):
  """
  FIX: The admin console displays a validation error because the output date format is wrongly generated by the admin widget.
  Environment: Dajngo 1.1 beta
  This widget forces the rigth format. You need to declare it in each form class inside the admin.py file. 
  See EmployeeChangeForm as an example.
  Norberto Ortigoza.
  """
  class Media:
    js = (settings.ADMIN_MEDIA_PREFIX + "js/calendar.js",
          settings.ADMIN_MEDIA_PREFIX + "js/admin/DateTimeShortcuts.js")

  def __init__(self, attrs={}):
    super(TTAdminDateWidget, self).__init__(format="%Y-%m-%d", attrs={'class': 'vDateField', 'size': '8'})
